apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandboxkbtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sandboxkbtest
    spec:
      containers:
      - name: sandboxkbtest
        image: otaviocordeiro/sandboxkbtest:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
        app: sandboxkbtest